name: Backend CI

on:
  pull_request:
    branches: [main]
    paths:
      - 'backend/**'
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'  # Adjust to match the required Python version

      - name: Install dependencies
        run: pipenv install --dev
        working-directory: backend

      - name: Run linter
        run: pipenv run lint
        working-directory: backend

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pipenv install --dev
        working-directory: backend

      - name: Run tests
        run: pipenv run test
        working-directory: backend

  build:
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Build Docker image
        run: docker build -t mp-backend:${{ github.sha }} .
        working-directory: backend
