name: Frontend Deployment

on:
  push:
    branches: [main]
    paths:
      - 'frontend/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Fetch IAM User ARN for github-action-user
        id: fetch-arn
        run: |
          USER_ARN=$(aws iam get-user --user-name github-action-user --query 'User.Arn' --output text)
          echo "USER_ARN=${USER_ARN}" >> $GITHUB_ENV

      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/

      - name: Install AWS IAM Authenticator
        run: |
          curl -Lo aws-iam-authenticator https://github.com/kubernetes-sigs/aws-iam-authenticator/releases/download/v0.6.2/aws-iam-authenticator_0.6.2_linux_amd64
          chmod +x aws-iam-authenticator
          sudo mv aws-iam-authenticator /usr/local/bin/

      - name: Update kubeconfig for EKS
        run: |
          aws eks update-kubeconfig --region ${{ secrets.AWS_REGION }} --name ${{ secrets.CLUSTER_NAME }}

      - name: Update aws-auth ConfigMap for GitHub Action User
        env:
          USER_ARN: ${{ env.USER_ARN }}
        run: |
          # Fetch the current aws-auth configmap and save it to a temporary file
          kubectl get configmap aws-auth -n kube-system -o yaml > aws-auth.yaml

          # Add github-action-user to the configmap with system:masters access
          echo "
          - rolearn: ${USER_ARN}
            username: github-action-user
            groups:
            - system:masters
          " >> aws-auth.yaml

          # Apply the updated configmap back to the cluster
          kubectl apply -f aws-auth.yaml

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push Docker image
        run: |
          docker build -t ${{ secrets.ECR_REPOSITORY_FRONTEND }}:latest frontend
          docker tag ${{ secrets.ECR_REPOSITORY_FRONTEND }}:latest ${{ secrets.ECR_REPOSITORY_FRONTEND }}:${{ github.sha }}
          docker push ${{ secrets.ECR_REPOSITORY_FRONTEND }}:${{ github.sha }}

      - name: Deploy to EKS
        run: |
          cd frontend/k8s
          kustomize edit set image frontend=${{ secrets.ECR_REPOSITORY_FRONTEND }}:${{ github.sha }}
          kustomize build | kubectl apply -f -
