name: Frontend Deployment

on:
  push:
    branches: [main]
    paths:
      - 'frontend/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          region: ${{ secrets.AWS_REGION }}

      - name: Build, tag, and push Docker image
        run: |
          docker build -t ${{ secrets.ECR_REPOSITORY_FRONTEND }}:latest frontend
          docker tag ${{ secrets.ECR_REPOSITORY_FRONTEND }}:latest ${{ secrets.ECR_REPOSITORY_FRONTEND }}:${{ github.sha }}
          docker push ${{ secrets.ECR_REPOSITORY_FRONTEND }}:${{ github.sha }}
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}

      - name: Update Kubernetes manifests
        run: |
          cd frontend/k8s
          kustomize edit set image frontend=${{ secrets.ECR_REPOSITORY_FRONTEND }}:${{ github.sha }}
          kustomize build | kubectl apply -f -
        env:
          KUBECONFIG: ~/.kube/config
